site_name: Pulp CLI
theme:
  name: readthedocs
  custom_dir: docs_theme
  version: "0.20.8.dev"
repo_url: https://github.com/pulp/pulp-cli
edit_uri: edit/main/docs/
markdown_extensions:
  - toc:
      permalink: True
  - admonition
nav:
  - 'Overview': 'index.md'
  - 'installation.md'
  - 'configuration.md'
  - 'using_the_cli.md'
  - 'supported_workflows.md'
  - 'advanced_features.md'
  - 'CHANGES.md'
  - 'contributing.md'
  - 'architecture.md'
