site_name: Pulp CLI
theme:
  name: readthedocs
  custom_dir: docs/theme
  version: "0.22.0.dev"
repo_url: https://github.com/pulp/pulp-cli
edit_uri: edit/main/docs/
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - attr_list
  - mkdocs-click
nav:
  - 'Overview': 'index.md'
  - 'installation.md'
  - 'configuration.md'
  - 'using_the_cli.md'
  - 'supported_workflows.md'
  - 'advanced_features.md'
  - 'CLI Command Reference': 'cli_reference.md'
  - 'CHANGES.md'
  - 'Developer material':
    - 'contributing.md'
    - 'architecture.md'
