site_name: Pulp CLI
theme:
  name: readthedocs
  custom_dir: docs_theme
  version: "0.23.0"
repo_url: https://github.com/pulp/pulp-cli
edit_uri: edit/main/docs/
markdown_extensions:
  - toc:
      permalink: True
  - admonition
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - pulp-glue/pulp_glue
          options:
            heading_level: 2
            show_root_heading: false
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            separate_signature: true
            members_order: "source"
            merge_init_into_class: true
nav:
  - 'Overview': 'index.md'
  - 'installation.md'
  - 'configuration.md'
  - 'using_the_cli.md'
  - 'supported_workflows.md'
  - 'advanced_features.md'
  - 'CHANGES.md'
  - 'Developer material':
    - 'contributing.md'
    - 'architecture.md'
  - 'Pulp Glue API Reference':
    - 'glue_reference/common_openapi.md'
    - 'glue_reference/common_context.md'
    - 'glue_reference/common_i18n.md'
    - 'glue_reference/core_context.md'
  - 'Pulp CLI plumbings API Reference':
    - 'cli_reference/common_generic.md'
