{%- import 'macros' as macros with context -%}
---
name: "Build"

on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      {{ macros.checkout() | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      - name: "Build wheels"
        run: |
          make build
          touch .root
      - name: "Upload wheels"
        uses: "actions/upload-artifact@v4"
        with:
          name: "pulp_cli_packages"
          path: |
            .root
            dist/
          if-no-files-found: "error"
          retention-days: 5
...
