---
name: "Build"

on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      {%- include "cache_action" %}
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.14"
      - name: "Install python dependencies"
        run: |
          pip install build setuptools wheel
      - name: "Build wheels"
        run: |
          make build
      - name: "Upload wheels"
        uses: "actions/upload-artifact@v4"
        with:
          name: "pulp_cli_packages"
          path: |
            pulp-glue{{ cookiecutter.__app_label_suffix }}/dist/
            dist/
          if-no-files-found: "error"
          retention-days: 5
...
