---
name: "Collect changes"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  collect-changes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
        with:
          ref: "main"
          fetch-depth: 0
      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.x"
      - name: "Setup git"
        run: |
          git config user.name pulpbot
          git config user.email pulp-infra@redhat.com
      - name: "Collect changes"
        run: |
          pip install GitPython packaging
          python3 .ci/scripts/collect_changes.py
      - name: "Create Pull Request"
        uses: "peter-evans/create-pull-request@v7"
        id: "create_pr"
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
          title: "Update Changelog"
          body: ""
          branch: "update_changes"
          delete-branch: true
      - name: "Mark PR automerge"
        run: |
          gh pr merge --rebase --auto "${{ steps.create_pr.outputs.pull-request-number }}"
        if: "steps.create_pr.outputs.pull-request-number"
        env:
          GH_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
        continue-on-error: true
...
