{%- import 'macros' as macros with context -%}
---
name: "pulp-cli CI"

on:
  pull_request:

{{ macros.concurrency() }}

jobs:
  lint:
    uses: "./.github/workflows/lint.yml"
  build:
    needs:
      - "lint"
    uses: "./.github/workflows/build.yml"
  test:
    needs:
      - "build"
    uses: "./.github/workflows/test.yml"
  {%- if cookiecutter.docs %}
  docs:
    needs:
      - "lint"
    # Keep the workflow tag the same as pulpdocs_ref.
    uses: "pulp/pulp-docs/.github/workflows/docs-ci.yml@main"
    with:
      pulpdocs_ref: "main"
  {%- endif %}
  codeql:
    needs:
      - "lint"
    uses: "./.github/workflows/codeql.yml"
  check-commits:
    runs-on: "ubuntu-latest"
    steps:
      {{ macros.checkout(deep=true) | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      - name: "Check commit message"
        env:
          {%- raw %}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_CONTEXT: "${{ github.event.pull_request.commits_url }}"
          {%- endraw %}
        run: |
          for SHA in $(curl -H "Authorization: token $GITHUB_TOKEN" "$GITHUB_CONTEXT" | jq -r '.[].sha')
          do
            uv run -q .ci/scripts/validate_commit_message.py "$SHA"
            VALUE=$?
            if [ "$VALUE" -gt 0 ]; then
              exit "$VALUE"
            fi
          done
        shell: "bash"
  ready-to-ship:
    # This is a dummy dependent task to have a single entry for the branch protection rules.
    runs-on: "ubuntu-latest"
    needs:
      - "check-commits"
      - "lint"
      - "test"
      {%- if cookiecutter.docs %}
      - "docs"
      {%- endif %}
      - "codeql"
    if: "always()"
    steps:
      - name: "Collect needed jobs results"
        run: |
          {%- raw %}
          echo '${{toJson(needs)}}' | jq -r 'to_entries[]|select(.value.result!="success")|.key + ": " + .value.result'
          echo '${{toJson(needs)}}' | jq -e 'to_entries|map(select(.value.result!="success"))|length == 0'
          echo "CI says: Looks good!"
          {%- endraw %}
...
