---
name: "Create Release Branch"
on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.x"
      - name: "Setup git"
        run: |
          git config user.name pulpbot
          git config user.email pulp-infra@redhat.com
      - name: "Install python dependencies"
        run: |
          pip install bump-my-version~=0.20.0
      - name: "Create Release Branch"
        run: |
          .ci/scripts/create_release_branch.sh
      - name: "Create Pull Request"
        uses: "peter-evans/create-pull-request@v7"
        id: "create_pr"
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
          title: "Bump dev-version"
          body: ""
          branch: "bump_version"
          delete-branch: true
      - name: "Mark PR automerge"
        run: |
          gh pr merge --rebase --auto "${{ steps.create_pr.outputs.pull-request-number }}"
        if: "steps.create_pr.outputs.pull-request-number"
        env:
          GH_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
        continue-on-error: true
      - name: "Add Backport Label for new Branch"
        uses: "actions/github-script@v8"
        with:
          script: |
            const { NEW_BRANCH } = process.env;
            const labelName = "backport-" + NEW_BRANCH;

            await github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: labelName,
              color: "C8780A",
            });
...
