---
name: "Build"

on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/*constraints.lock', '**/setup.py', '**/pyproject.toml') }}"
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "Install python dependencies"
        run: |
          pip install build setuptools wheel
      - name: "Build wheels"
        run: |
          make build
      - name: "Upload wheels"
        uses: "actions/upload-artifact@v4"
        with:
          name: "pulp_cli_packages"
          path: |
            pulp-glue/dist/
            dist/
          if-no-files-found: "error"
          retention-days: 5
...
